version: "3"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - init
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./data/sonarqube_data:/opt/sonarqube/data
      - ./data/sonarqube_extensions:/opt/sonarqube/extensions
      - ./data/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  init:
    image: bash
    container_name: init
    privileged: true
    user: root
    volumes:
      - ./init/init_sysctl.sh:/mnt/init_sysctl.sh
    command: [ "sh", "-e", "/mnt/init_sysctl.sh" ]

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      - ./data/postgresql_data:/var/lib/postgresql/data

volumes:
  init:
  data: